### PR TITLE
Add mailer locale doc

### PR DESCRIPTION
**Pull request by aarona**
Because I pass the email address being confirmed to the response message like so:

    message: I18n.t('graphql_devise.confirmations.send_instructions', email: email)

I thought that it should be documented for the user in case they wanted to customize the locale to support it. This is supported by Devise even though our locale setting doesn't. The user would have to override the entire mutation to put the email variable in there otherwise which is why I left it in.

I decided to add this documentation as a subset in the **Customizing Email Templates** section because I felt that was the best place to put it.

### CODE REVIEW

**Comment by aarona** [comment]
Ok, so you think I should move this to an I18n section and put an example like the ones used in the link you posted to show that the user could have something like:
```yml
en:
  graphql_devise:
    confirmations:
      send_instructions: "Please check '#{email}' for instructions on how to confirm your account"
```

Something like that?

**Comment by mcelicalderon** [comment]
Yes, something more generic like Devise's, not only for the resend confirmation email. More importantly, provide a link to our file on the repo where they could see ALL the locales they can override

**Comment by aarona** [comment]
Ok, I'll look into this, this weekend and update the PR.

**Comment by aarona** [comment]
Finally got around to adding a separate section for I18n.

**Comment by 00dav00** [comment]
Thanks @aarona, this looks like a nice addition.

**Pull request merged**
