### PR TITLE
Add support for graphql 1.13

### PR DESCRIPTION
**Pull request by mcelicalderon**
Adds support for graphql 1.13

Fixes test matrix and appraisals. Temporarily skipping rails 7.0. Spec support will be fixed in a follow up PR

### CODE REVIEW

**Comment by mcelicalderon** [comment]
@00dav00 can you please take a look? I had to disable testing Rails 7.0 temporarily to fix master. Will fix in a follow up MR, there seems to be something wrong with the generator.

**Review by 00dav00 — APPROVED** [review]

**Comment by janraasch** [comment]
Hi there 👋, thank you for your work on this nice gem 👍 🙏. Do you have en ETA for when you'll be able to **release a version** of `graphql_devise` sporting that sweet `graphql 1.13`-version support 🤓?

**Comment by mcelicalderon** [comment]
Hey @janraasch! Sorry this got lost in master. We've been waiting to do a bigger release with everything in master, but perhaps we can release this change separately. I'll try to do so later today, no reason to delay support for 1.13 as no code changes were actually required

**Comment by janraasch** [comment]
Sounds great, @mcelicalderon 💜. Thank you!

**Comment by mcelicalderon** [comment]
v0.18.0 released with graphql 1.13 support @janraasch

**Pull request merged**
