### PR TITLE
Fix for rails 7.1

### PR DESCRIPTION
**Pull request by scott-knight**
Removed the Rails version cap. Now I can use Rails 7.1!!!

### CODE REVIEW

**Comment by mcelicalderon** [comment]
Thank you, @scott-knight! You'll need to update our test version matrix in order to make sure there are no problems with this version of rails. You can give it a try if you want, here's a similar MR https://github.com/graphql-devise/graphql_devise/pull/241/files (just use what might be related to adding the new version)

**Comment by mcelicalderon** [comment]
And we do need to cap the rails version in the gemspec since if ew don't, this version of the gem will assume it works for any future version of rails. So you could cap it to `< 7.2`

**Comment by scott-knight** [comment]
Hi @mcelicalderon , thanks for getting back to me. I can set the cap for sure, but I'm not sure about the other updates as outlined in  https://github.com/graphql-devise/graphql_devise/pull/241/files  (some of that looks autogenerated, maybe?). Is there a way to all updates for the test version matrix without making a mistake (LOL)?

**Comment by mcelicalderon** [comment]
@scott-knight again than you for looking into this. While creating the appraisals for Rails 7.1 I realized that Devise token auth hasn't released a version that supports Rails 7.1 yet, but support has already been merged into master https://github.com/lynndylanhurley/devise_token_auth/blob/6b0659f18c678b319913d0fb053e96aa555857aa/devise_token_auth.gemspec

So, just like last time, we need to wait for them to release a version with Rails 7.1 support, before we can do the same here as that gem is a dependency of this one

**Comment by scott-knight** [comment]
@mcelicalderon sounds good. I have all the gems forked and updated for my app for now. I can wait until the official updates are released. I appreciate your input.

**Comment by mcelicalderon** [comment]
I'm closing this one in favor of https://github.com/graphql-devise/graphql_devise/pull/267 since supporting the new version will require additional work around the test matrix

**Pull request closed without merging**
