### PR TITLE
Support Rails 7.1

### PR DESCRIPTION
**Pull request by mcelicalderon**

### CODE REVIEW

**Comment by saurabhbhatia** [comment]
Keen on this PR, I believe a blocker for this could be that Rails 7.1 support is WIP in devise_token_auth as well.

https://github.com/lynndylanhurley/devise_token_auth/issues/1608

**Comment by mcelicalderon** [comment]
That is correct @saurabhbhatia, and I see dta already merged support into master. They just have to release a new version with that change

**Comment by saurabhbhatia** [comment]
Yeah makes sense @mcelicalderon looking forward to the change here as well, great work 👍

**Comment by scott-knight** [comment]
https://github.com/lynndylanhurley/devise_token_auth now supports Rails 7.1

**Comment by mcelicalderon** [comment]
Not yet, merged into master but they need to release a new version to ruby gems

**Comment by t2** [comment]
@mcelicalderon looks like devise_token_auth is ready to go now, correct? Need help getting this merged?

**Comment by mcelicalderon** [comment]
> @mcelicalderon looks like devise_token_auth is ready to go now, correct? Need help getting this merged?

Yes, @t2! It looks like they released the new version today 🙌 We'll release a new version too

**Pull request merged**
